# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kimberly Ann Keller
description: > # this means to ignore newlines until "baseurl:"
  I'm a passionate software developer. I love learning about new 
  ideas and technologies. In my spare time I like reading and spending time with my chickens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kimberlyannkeller.com" # the base hostname & protocol for your site
github_username:  kimberlykeller

# Build settings
markdown: kramdown

sass:
  style: compressed
